version: '3.7'

services:
  web:
    build: .
    environment:
      ENV: "Development"
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1
    volumes:
      - '.:/web'
    ports:
      - '8000:8000'